name: Project Publish
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    if: ${{ startsWith(gitea.event.pull_request.labels[0].name, 'Project/Release') && gitea.event.pull_request.milestone != null && gitea.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: tiagomta/checkout@v1
      - name: Publish Package (Gitea)
        uses: tiagomta/npm@v1
        with:
          command: publish --scope vistta --registry https://git.vistta.org/api/packages/vistta/npm/ --tag stable
          token: ${{ secrets.TOKEN }}
      - name: Tag
        id: tag
        uses: tiagomta/npm@v1
        with:
          command: version tag --email devops@vistta.org --force
      - name: Close Milestone
        uses: tiagomta/gitea@v1
        with:
          command: milestone close ${{ gitea.event.pull_request.milestone.id }}
      - name: Create Release
        uses: tiagomta/gitea@v1
        with:
          command: release create ${{ steps.tag.outputs.result }} --fromMilestone ${{ gitea.event.pull_request.milestone.id }}
