name: Project Setup
on:
  pull_request:
    types: [labeled]
    branches:    
      - master
env:
  module: utils
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    if: ${{ startsWith(gitea.event.pull_request.labels[0].name, 'Project/Release') && gitea.event.pull_request.milestone == null }}
    steps:
      - 
        name: Checkout
        uses: tiagomta/checkout@v1
        with:
          repository: vistta/vistta
          ref: ${{ gitea.event.pull_request.head.ref }}
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - 
        name: Release Patch
        if: ${{ endsWith(gitea.event.pull_request.labels[0].name, 'Patch') }}
        id: patch
        uses: tiagomta/npm@v1
        with:
          command: version patch --email devops@vistta.org
          working-directory: ./packages/${{ env.module }}
      - 
        name: Create Patch Milestone
        if: ${{ endsWith(gitea.event.pull_request.labels[0].name, 'Patch') }}
        uses: tiagomta/gitea@v1
        with:
          command: milestone create "Patch (v${{ steps.patch.outputs.result }})" --linkPR
      - 
        name: Release Minor
        if: ${{ endsWith(gitea.event.pull_request.labels[0].name, 'Minor') }}
        id: minor
        uses: tiagomta/npm@v1
        with:
          command: version minor --email devops@vistta.org
          working-directory: ./packages/${{ env.module }}
      - 
        name: Create Minor Milestone
        if: ${{ endsWith(gitea.event.pull_request.labels[0].name, 'Minor') }}
        uses: tiagomta/gitea@v1
        with:
          command: milestone create "Minor (v${{ steps.minor.outputs.result }})" --linkPR
      - 
        name: Release Major
        if: ${{ endsWith(gitea.event.pull_request.labels[0].name, 'Major') }}
        id: major
        uses: tiagomta/npm@v1
        with:
          command: version major --email devops@vistta.org
          working-directory: ./packages/${{ env.module }}
      - 
        name: Create Major Milestone
        if: ${{ endsWith(gitea.event.pull_request.labels[0].name, 'Major') }}
        uses: tiagomta/gitea@v1
        with:
          command: milestone create "Major (v${{ steps.major.outputs.result }})" --linkPR